using System;

namespace MotoBest.Tests.Scraping.DesktopAutoBg;

public static class DesktopAutoBgScrapedModels
{
    public static readonly string[] Pobeda = Array.Empty<string>();

    public static readonly string[] AlfaRomeo = new[]
    {
        "145",
        "146",
        "147",
        "155",
        "156",
        "156 sportwagon",
        "159",
        "159 sportwagon",
        "164",
        "166",
        "33",
        "4C",
        "75",
        "76",
        "8C Competizione",
        "90",
        "Alfetta",
        "Berlina",
        "Brera",
        "Crosswagon q4",
        "Giulia",
        "Giulietta",
        "Gt",
        "Gtv",
        "MiTo",
        "Spider",
        "Sprint",
        "Stelvio",
        "Sud",
    };

    public static readonly string[] Honda = new[]
    {
        "Accord",
        "Cbr",
        "Cbx",
        "City",
        "Civic",
        "Civic ballade",
        "Concerto",
        "Cr-v",
        "Crosstour",
        "Crx",
        "Crz",
        "Electric",
        "Element",
        "Elysion",
        "Fit",
        "Fr-v",
        "Hr-v",
        "Insight",
        "Integra",
        "Jazz",
        "Legend",
        "Logo",
        "Nsx",
        "Odyssey",
        "Passport",
        "Pilot",
        "Prelude",
        "Quintet",
        "Ridgeline",
        "S2000",
        "Shuttle",
        "Stream",
    };

    public static readonly string[] Peugeot = new[]
    {
        "1007",
        "104",
        "106",
        "107",
        "108",
        "2008",
        "202",
        "204",
        "205",
        "206",
        "207",
        "208",
        "3008",
        "301",
        "304",
        "305",
        "306",
        "307",
        "308",
        "309",
        "4007",
        "4008",
        "402",
        "403",
        "404",
        "405",
        "406",
        "407",
        "5008",
        "504",
        "505",
        "508",
        "604",
        "605",
        "607",
        "806",
        "807",
        "Bipper",
        "Expert",
        "iOn",
        "Partner",
        "Range",
        "RCZ",
        "Rifter",
        "Traveler",
    };
}
