select * from Transmissions;
select * from Engines;
select * from Colors;
select * from Conditions;
select * from Regions;
select * from BodyStyles;
select * from Brands;
select * from EuroStandards;
select count(*) from PopulatedPlaces;
